"""
generate-loader command: generate _xforge_loader.py for plugin packages.
"""
import argparse
import os
import sys
from pathlib import Path

from xforge.precompiled.options import XforgeOptions

_CRATE_SEARCH_PATHS = [".", "native", "rust", "../native", "../rust", "../.."]

_LOADER_TEMPLATE = '''\
# AUTO-GENERATED by xforge generate-loader. Do not edit manually.
# Re-run: xforge generate-loader --out {out_path}
"""
Auto-loader for the precompiled native library.
Imported at package init time; downloads and loads the library transparently.
"""
import ctypes
from xforge.precompiled.loader import load_or_raise

LIBRARY: ctypes.CDLL = load_or_raise(
    crate_dir=__file__,
    crate_rel_path={crate_rel_path!r},
    fallback_builder=None,  # replace with your own build function if needed
)
'''


def run_generate_loader(rest: list[str]) -> int:
    p = argparse.ArgumentParser(prog="xforge generate-loader")
    p.add_argument(
        "--crate-dir",
        default=None,
        help="Crate directory containing xforge.yaml (auto-detected if omitted)",
    )
    p.add_argument(
        "--out",
        default="_xforge_loader.py",
        help="Output file path (default: ./_xforge_loader.py)",
    )
    parsed, _ = p.parse_known_args(rest)

    out_path = Path(parsed.out).resolve()

    if parsed.crate_dir:
        crate_dir = Path(parsed.crate_dir).resolve()
        if not (crate_dir / "xforge.yaml").is_file():
            print(f"Error: xforge.yaml not found in {crate_dir}", file=sys.stderr)
            return 2
    else:
        crate_dir = _autodetect_crate_dir()
        if crate_dir is None:
            print(
                "Error: could not find xforge.yaml. "
                f"Searched: {_CRATE_SEARCH_PATHS}. "
                "Use --crate-dir to specify the crate directory.",
                file=sys.stderr,
            )
            return 2

    options = XforgeOptions.load(crate_dir)
    if options.precompiled_binaries is None:
        print(
            f"Error: xforge.yaml at {crate_dir} has no precompiled_binaries block.",
            file=sys.stderr,
        )
        return 2

    try:
        crate_rel_path = os.path.relpath(crate_dir, out_path.parent)
    except ValueError:
        crate_rel_path = str(crate_dir)

    content = _LOADER_TEMPLATE.format(
        out_path=out_path.name,
        crate_rel_path=crate_rel_path,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Generated: {out_path}")
    print(f"  crate_dir: {crate_dir}")
    print(f"  crate_rel_path: {crate_rel_path!r}")
    return 0


def _autodetect_crate_dir() -> Path | None:
    cwd = Path.cwd()
    for rel in _CRATE_SEARCH_PATHS:
        candidate = (cwd / rel).resolve()
        if (candidate / "xforge.yaml").is_file():
            return candidate
    return None
