"""
CLI: keygen, validate-precompiled, generate-loader. Entry point for the xforge script.
"""
import argparse
import os
import sys
from pathlib import Path

from nacl.encoding import RawEncoder
from nacl.signing import SigningKey

from xforge import (
    XforgeOptions,
    compute_release_hash,
    detect_host_target_triple,
)
from xforge.artifacts_provider import PrecompiledArtifactsProvider
from xforge.util import hex_encode


def main() -> None:
    argv = sys.argv[1:]
    if not argv or argv[0] in ("--help", "-h"):
        print("xforge commands: keygen, validate-precompiled, generate-loader")
        print("Run with --help for command options.")
        sys.exit(0 if argv and argv[0] in ("--help", "-h") else 2)

    parser = argparse.ArgumentParser(
        prog="xforge",
        description="xforge-python CLI: keygen, validate-precompiled, generate-loader",
    )
    parser.add_argument(
        "command",
        choices=["keygen", "validate-precompiled", "generate-loader"],
        help="Command to run",
    )
    parser.add_argument(
        "extra",
        nargs=argparse.REMAINDER,
        default=[],
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args(argv)

    if args.command == "keygen":
        sys.exit(run_keygen(args.extra))
    if args.command == "validate-precompiled":
        sys.exit(run_validate_precompiled(args.extra))
    if args.command == "generate-loader":
        sys.exit(run_generate_loader(args.extra))
    parser.print_help()
    sys.exit(2)


def run_keygen(rest: list[str]) -> int:
    if rest and rest != ["--help"] and rest != ["-h"]:
        print("Unknown arguments: " + " ".join(rest), file=sys.stderr)
        _print_keygen_usage()
        return 2
    if rest and rest[0] in ("--help", "-h"):
        _print_keygen_usage()
        return 0

    signing_key = SigningKey.generate()
    seed = signing_key.encode(encoder=RawEncoder)
    verify_key = signing_key.verify_key
    public = verify_key.encode(encoder=RawEncoder)
    # xforge expects private_key = seed (32) + public (32)
    private = seed + public

    if len(public) != 32 or len(private) != 64:
        print(
            "Key generation failed: expected 32-byte public key and "
            "64-byte private key.",
            file=sys.stderr,
        )
        return 1

    print(f"public_key={hex_encode(public)}")
    print(f"private_key={hex_encode(private)}")
    return 0


def _print_keygen_usage() -> None:
    print("Usage: xforge keygen")
    print("Outputs:")
    print("  public_key=<32-byte hex>")
    print("  private_key=<64-byte hex (seed + public)>")


def run_validate_precompiled(rest: list[str]) -> int:
    p = argparse.ArgumentParser(prog="xforge validate-precompiled")
    p.add_argument(
        "--crate-dir",
        default=None,
        help="Crate directory (default: cwd)",
    )
    p.add_argument(
        "--build-id",
        default=None,
        help="Build id override",
    )
    p.add_argument(
        "--target",
        default=None,
        help="Rust target triple (default: host)",
    )
    parsed, _ = p.parse_known_args(rest)

    crate_dir = Path(parsed.crate_dir) if parsed.crate_dir else Path.cwd()

    options = XforgeOptions.load(crate_dir)
    config = options.precompiled_binaries
    if config is None:
        print("xforge.yaml is missing precompiled_binaries config.", file=sys.stderr)
        return 2

    build_id = parsed.build_id or compute_release_hash(crate_dir)
    target = parsed.target or detect_host_target_triple()

    provider = PrecompiledArtifactsProvider(
        crate_dir=crate_dir,
        config=config,
    )

    try:
        manifest = provider.fetch_verified_manifest(build_id)
        selection = provider.select_artifact(manifest=manifest, target=target)
        provider.fetch_verified_artifact(
            build_id=build_id,
            artifact_name=selection.artifact_name,
        )
        print("Validated precompiled artifact:")
        print(f"  crateDir: {crate_dir.resolve()}")
        print(f"  buildId: {build_id}")
        print(f"  target: {target}")
        print(f"  artifact: {selection.artifact_name}")
        return 0
    except Exception as e:
        print(f"Validation failed: {e}", file=sys.stderr)
        return 1


_CRATE_SEARCH_PATHS = [".", "native", "rust", "../native", "../rust", "../.."]

_LOADER_TEMPLATE = '''\
# AUTO-GENERATED by xforge generate-loader. Do not edit manually.
# Re-run: xforge generate-loader --out {out_path}
"""
Auto-loader for the precompiled native library.
Imported at package init time; downloads and loads the library transparently.
"""
import ctypes
from xforge.loader import load_or_raise

LIBRARY: ctypes.CDLL = load_or_raise(
    crate_dir=__file__,
    crate_rel_path={crate_rel_path!r},
    fallback_builder=None,  # replace with your own build function if needed
)
'''


def run_generate_loader(rest: list[str]) -> int:
    p = argparse.ArgumentParser(prog="xforge generate-loader")
    p.add_argument(
        "--crate-dir",
        default=None,
        help="Crate directory containing xforge.yaml (auto-detected if omitted)",
    )
    p.add_argument(
        "--out",
        default="_xforge_loader.py",
        help="Output file path (default: ./_xforge_loader.py)",
    )
    parsed, _ = p.parse_known_args(rest)

    out_path = Path(parsed.out).resolve()

    # Resolve crate dir
    if parsed.crate_dir:
        crate_dir = Path(parsed.crate_dir).resolve()
        if not (crate_dir / "xforge.yaml").is_file():
            print(
                f"Error: xforge.yaml not found in {crate_dir}",
                file=sys.stderr,
            )
            return 2
    else:
        crate_dir = _autodetect_crate_dir()
        if crate_dir is None:
            print(
                "Error: could not find xforge.yaml. "
                f"Searched: {_CRATE_SEARCH_PATHS}. "
                "Use --crate-dir to specify the crate directory.",
                file=sys.stderr,
            )
            return 2

    # Validate precompiled_binaries block exists
    options = XforgeOptions.load(crate_dir)
    if options.precompiled_binaries is None:
        print(
            f"Error: xforge.yaml at {crate_dir} has no precompiled_binaries block.",
            file=sys.stderr,
        )
        return 2

    # Compute relative path from the output file's directory to the crate dir
    try:
        crate_rel_path = os.path.relpath(crate_dir, out_path.parent)
    except ValueError:
        # On Windows, relpath can fail across drives — fall back to absolute
        crate_rel_path = str(crate_dir)

    content = _LOADER_TEMPLATE.format(
        out_path=out_path.name,
        crate_rel_path=crate_rel_path,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Generated: {out_path}")
    print(f"  crate_dir: {crate_dir}")
    print(f"  crate_rel_path: {crate_rel_path!r}")
    return 0


def _autodetect_crate_dir() -> Path | None:
    cwd = Path.cwd()
    for rel in _CRATE_SEARCH_PATHS:
        candidate = (cwd / rel).resolve()
        if (candidate / "xforge.yaml").is_file():
            return candidate
    return None
